/* Création de la base de données BI et des tables associées */
CREATE DATABASE IF NOT EXISTS BI;
USE BI;

/* Suppression des tables dans un ordre sécurisé pour éviter les conflits de clés étrangères*/
DROP TABLE IF EXISTS PARTICIPATION;
DROP TABLE IF EXISTS BORNE;
DROP TABLE IF EXISTS CAPTEURS;
DROP TABLE IF EXISTS JEUX;
DROP TABLE IF EXISTS TYPE_CAPTEUR;
DROP TABLE IF EXISTS TYPE_GAIN;
DROP TABLE IF EXISTS TYPE_UTILISATEUR;
DROP TABLE IF EXISTS UTILISATEUR;

/* Création de la table UTILISATEUR */
CREATE TABLE UTILISATEUR (
    ID_UTILISATEUR       INT NOT NULL,
    ID_TYPE_UTILISATEUR  INT NOT NULL,
    NOM_UTILISATEUR      CHAR(20) NULL,
    PRENOM_UTILISATEUR   CHAR(20) NULL,
    EMAIL_UTILISATEUR    VARCHAR(30) NULL,
    MDP_UTILISATEUR      VARCHAR(20) NULL, 
    PRIMARY KEY (ID_UTILISATEUR)
) ENGINE=InnoDB;

/* Création de la table TYPE_UTILISATEUR */
CREATE TABLE TYPE_UTILISATEUR (
    ID_TYPE_UTILISATEUR      INT NOT NULL,
    LIBELLE_TYPE_UTILISATEUR CHAR(20) NULL,
    PRIMARY KEY (ID_TYPE_UTILISATEUR)
) ENGINE=InnoDB;

/* Création de la table JEUX */
CREATE TABLE JEUX (
    ID_JEU      INT NOT NULL,
    NOM_JEU     CHAR(20) NULL,
    DESCRIPTION VARCHAR(255) NULL,
    PRIMARY KEY (ID_JEU)
) ENGINE=InnoDB;

/* Création de la table TYPE_GAIN */
CREATE TABLE TYPE_GAIN (
    ID_TYPE_GAIN      INT NOT NULL,
    LIBELLE_TYPE_GAIN CHAR(20) NULL,
    PRIMARY KEY (ID_TYPE_GAIN)
) ENGINE=InnoDB;

/* Création de la table PARTICIPATION */
CREATE TABLE PARTICIPATION (
    ID_JEU                 INT NOT NULL,
    ID_TYPE_GAIN           INT NOT NULL,
    RESULTAT_PARTICIPATION SMALLINT NULL,
    PRIMARY KEY (ID_JEU, ID_TYPE_GAIN)
) ENGINE=InnoDB;

/* Création de la table BORNE */
CREATE TABLE BORNE (
    ID_BORNE        INT NOT NULL,
    ID_UTILISATEUR  INT NULL, 
    ID_CAPTEUR      INT NULL,
    ID_JEU          INT NULL,
    ETAT            CHAR(20) NULL,
    PRIMARY KEY (ID_BORNE)
) ENGINE=InnoDB;

/* Création de la table CAPTEURS */
CREATE TABLE CAPTEURS (
    ID_CAPTEUR         INT NOT NULL,
    ID_TYPE_CAPTEUR    INT NOT NULL,
    VALEUR1            CHAR(20) NULL,
    VALEUR2            CHAR(20) NULL,
    PRIMARY KEY (ID_CAPTEUR)
) ENGINE=InnoDB;

/* Création de la table TYPE_CAPTEUR */
CREATE TABLE TYPE_CAPTEUR (
    ID_TYPE_CAPTEUR      INT NOT NULL,
    LIBELLE_TYPE_CAPTEUR CHAR(20) NULL,
    PRIMARY KEY (ID_TYPE_CAPTEUR)
) ENGINE=InnoDB;

/* Ajout des index pour optimiser les requêtes */
CREATE INDEX PARTICIPATION_FK ON PARTICIPATION (ID_JEU);
CREATE INDEX PARTICIPATION_TYPE_GAIN_FK ON PARTICIPATION (ID_TYPE_GAIN);

CREATE INDEX BORNE_JEU_FK ON BORNE (ID_JEU);
CREATE INDEX BORNE_UTILISATEUR_FK ON BORNE (ID_UTILISATEUR);
CREATE INDEX BORNE_CAPTEUR_FK ON BORNE (ID_CAPTEUR);

CREATE INDEX CAPTEURS_TYPE_CAPTEUR_FK ON CAPTEURS (ID_TYPE_CAPTEUR);

CREATE INDEX UTILISATEUR_TYPE_UTILISATEUR_FK ON UTILISATEUR (ID_TYPE_UTILISATEUR);

/* Ajout des contraintes de clés étrangères */
ALTER TABLE UTILISATEUR
    ADD CONSTRAINT FK_UTILISAT_ASSOCIATI_TYPE_UTI 
    FOREIGN KEY (ID_TYPE_UTILISATEUR) REFERENCES TYPE_UTILISATEUR(ID_TYPE_UTILISATEUR)
    ON UPDATE RESTRICT ON DELETE RESTRICT; # Vérifier si ces restrictions sont adaptées

ALTER TABLE PARTICIPATION
    ADD CONSTRAINT FK_PARTICIPATION_TYPE_GAIN 
    FOREIGN KEY (ID_TYPE_GAIN) REFERENCES TYPE_GAIN(ID_TYPE_GAIN)
    ON UPDATE RESTRICT ON DELETE RESTRICT,
    ADD CONSTRAINT FK_PARTICIPATION_JEUX 
    FOREIGN KEY (ID_JEU) REFERENCES JEUX(ID_JEU)
    ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE BORNE
    ADD CONSTRAINT FK_BORNE_JEUX 
    FOREIGN KEY (ID_JEU) REFERENCES JEUX(ID_JEU)
    ON UPDATE RESTRICT ON DELETE RESTRICT,
    ADD CONSTRAINT FK_BORNE_UTILISATEUR 
    FOREIGN KEY (ID_UTILISATEUR) REFERENCES UTILISATEUR(ID_UTILISATEUR)
    ON UPDATE RESTRICT ON DELETE RESTRICT,
    ADD CONSTRAINT FK_BORNE_CAPTEURS 
    FOREIGN KEY (ID_CAPTEUR) REFERENCES CAPTEURS(ID_CAPTEUR)
    ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE CAPTEURS
    ADD CONSTRAINT FK_CAPTEURS_TYPE_CAP 
    FOREIGN KEY (ID_TYPE_CAPTEUR) REFERENCES TYPE_CAPTEUR(ID_TYPE_CAPTEUR)
    ON UPDATE RESTRICT ON DELETE RESTRICT;
